### ISSUE TITLE
Issue to publish plaid config file

### ISSUE THREAD

**Issue by husonghua** [travoltron/plaid#5]
When I use: php artisan vendor:publish --provider="Travoltron\Plaid\PlaidServiceProvider" --tag="config"
I got: Nothing to publish for tag [config].

I believe that's because the file was not properly tagged.

**Comment by travoltron** [comment]
I've updated the documentation to include a missing step, you may want to re-get the package, it's now running Guzzle 6, but if you're happy to use 5.3 (it won't make much of a difference either way), you can add 

`Travoltron\Plaid\PlaidServiceProvider::class,`

to the providers array in `config/app.php` and then retrigger the `vendor:publish` command. 

Thanks for mentioning that, sorry I missed that blurb in the docs.

**Comment by husonghua** [comment]
Thanks! 

By the way, I just downgraded guzzle to 5 this afternoon to make the library work. I guess I will kick it up back to 6 now:-).

**Comment by travoltron** [comment]
Thanks for the reply, happy to have any feedback.
