### ISSUE TITLE
Call to a member function getBody() on null

### ISSUE THREAD

**Issue by bfblackjack** [travoltron/plaid#7]
After attempting to call the addAuthUser function on the Plaid facade, I get a returned error of...

Call to a member function getBody() on null

This looks like a guzzle error of sorts, I'm guessing the request is failing but I am not sure why.

**Comment by travoltron** [comment]
Which version of the library are you using? I'm currently in the middle of a rewrite to 2.0, which includes routing/testing. Perhaps the bug is somewhere in some less than completed code.

**Comment by bfblackjack** [comment]
It looks like composer is using 2.0

**Comment by travoltron** [comment]
Ok, do you mind emailing me the sample code, and the output? Inclusive of the error lines/files? ben@travoltron.com 

Thanks!

**Comment by bfblackjack** [comment]
I am literally just calling Plaid::addAuthUser($username, $password, $pin, $type) where all 4 variables are strings. $pin is null.

**Comment by travoltron** [comment]
I'll try and recreate it now. For testing, I'll be using the default credentials of "plaid_test" for username, "plaid_good" for password, and "wells" for type.

**Comment by travoltron** [comment]
I figured out what the snag is: you haven't published the config file for the package. 

`php artisan vendor:publish --provider="Travoltron\Plaid\PlaidServiceProvider" --tag="config"`

Try that and let me know what you see.

Thanks!

**Comment by travoltron** [comment]
Any update on that error? Closing the issue, but feel free to message again if you have any further trouble.

**Comment by bfblackjack** [comment]
It works! I published it previously but I may have managed to delete it and forget to republish it as I was trying to diagnose the error initially (not sure how that happened.) Thanks!

**Comment by gigalabs18** [comment]
same error i have publish the config file also.

**Comment by gigalabs18** [comment]
> I figured out what the snag is: you haven't published the config file for the package.
> 
> `php artisan vendor:publish --provider="Travoltron\Plaid\PlaidServiceProvider" --tag="config"`
> 
> Try that and let me know what you see.
> 
> Thanks!

same error i have publish the config file also.
